enum JobState {
    None = 0,
    Registered = 1 << 0,
    Starting = 1 << 1,
    Started = 1 << 2,
    Finalizing = 1 << 3,
    Completed = 1 << 4,
    Waiting = 1 << 5,
    ConsumerInputRequired = 1 << 6,
    EncounteredErrors = 1 << 7,
    EncounteredWarnings = 1 << 8,
    ConsumerCancelled = 1 << 9,
    RegisteredWithWarnings = Registered | EncounteredWarnings,
    RegisteredWithErrors = Registered | EncounteredErrors,
    WaitingDueToWarnings = Waiting | EncounteredWarnings,
    WaitingDueToErrors = Waiting | EncounteredErrors,
    WaitingOnConsumer = Waiting | ConsumerInputRequired,
    CompletedWithWarnings = Completed | EncounteredWarnings,
    CompletedWithErrors = Completed | EncounteredErrors,
    CompletedThroughCancellation = Completed | ConsumerCancelled
};